<template>
  <div id="my">
    <nav-bar class="my-nav">
      <div slot="center">我的</div>
    </nav-bar>
    <ul class='content'>
      <li>1</li>
      <li>2</li>
      <li>3</li>
      <li>4</li>
      <li>5</li>
      <li>6</li>
      <li>7</li>
      <li>8</li>
      <li>9</li>
      <li>10</li>
      <li>11</li>
      <li>12</li>
      <li>13</li>
      <li>14</li>
      <li>15</li>
      <li>16</li>
      <li>17</li>
      <li>18</li>
      <li>19</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>1</li>
      <li>2</li>
      <li>3</li>
      <li>4</li>
      <li>5</li>
      <li>6</li>
      <li>7</li>
      <li>8</li>
      <li>9</li>
      <li>10</li>
      <li>11</li>
      <li>12</li>
      <li>13</li>
      <li>14</li>
      <li>15</li>
      <li>16</li>
      <li>17</li>
      <li>18</li>
      <li>19</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>1</li>
      <li>2</li>
      <li>3</li>
      <li>4</li>
      <li>5</li>
      <li>6</li>
      <li>7</li>
      <li>8</li>
      <li>9</li>
      <li>10</li>
      <li>11</li>
      <li>12</li>
      <li>13</li>
      <li>14</li>
      <li>15</li>
      <li>16</li>
      <li>17</li>
      <li>18</li>
      <li>19</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>1</li>
      <li>2</li>
      <li>3</li>
      <li>4</li>
      <li>5</li>
      <li>6</li>
      <li>7</li>
      <li>8</li>
      <li>9</li>
      <li>10</li>
      <li>11</li>
      <li>12</li>
      <li>13</li>
      <li>14</li>
      <li>15</li>
      <li>16</li>
      <li>17</li>
      <li>18</li>
      <li>19</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>1</li>
      <li>2</li>
      <li>3</li>
      <li>4</li>
      <li>5</li>
      <li>6</li>
      <li>7</li>
      <li>8</li>
      <li>9</li>
      <li>10</li>
      <li>11</li>
      <li>12</li>
      <li>13</li>
      <li>14</li>
      <li>15</li>
      <li>16</li>
      <li>17</li>
      <li>18</li>
      <li>19</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>1</li>
      <li>2</li>
      <li>3</li>
      <li>4</li>
      <li>5</li>
      <li>6</li>
      <li>7</li>
      <li>8</li>
      <li>9</li>
      <li>10</li>
      <li>11</li>
      <li>12</li>
      <li>13</li>
      <li>14</li>
      <li>15</li>
      <li>16</li>
      <li>17</li>
      <li>18</li>
      <li>19</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>1</li>
      <li>2</li>
      <li>3</li>
      <li>4</li>
      <li>5</li>
      <li>6</li>
      <li>7</li>
      <li>8</li>
      <li>9</li>
      <li>10</li>
      <li>11</li>
      <li>12</li>
      <li>13</li>
      <li>14</li>
      <li>15</li>
      <li>16</li>
      <li>17</li>
      <li>18</li>
      <li>19</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>1</li>
      <li>2</li>
      <li>3</li>
      <li>4</li>
      <li>5</li>
      <li>6</li>
      <li>7</li>
      <li>8</li>
      <li>9</li>
      <li>10</li>
      <li>11</li>
      <li>12</li>
      <li>13</li>
      <li>14</li>
      <li>15</li>
      <li>16</li>
      <li>17</li>
      <li>18</li>
      <li>19</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>1</li>
      <li>2</li>
      <li>3</li>
      <li>4</li>
      <li>5</li>
      <li>6</li>
      <li>7</li>
      <li>8</li>
      <li>9</li>
      <li>10</li>
      <li>11</li>
      <li>12</li>
      <li>13</li>
      <li>14</li>
      <li>15</li>
      <li>16</li>
      <li>17</li>
      <li>18</li>
      <li>19</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>1</li>
      <li>2</li>
      <li>3</li>
      <li>4</li>
      <li>5</li>
      <li>6</li>
      <li>7</li>
      <li>8</li>
      <li>9</li>
      <li>10</li>
      <li>11</li>
      <li>12</li>
      <li>13</li>
      <li>14</li>
      <li>15</li>
      <li>16</li>
      <li>17</li>
      <li>18</li>
      <li>19</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>1</li>
      <li>2</li>
      <li>3</li>
      <li>4</li>
      <li>5</li>
      <li>6</li>
      <li>7</li>
      <li>8</li>
      <li>9</li>
      <li>10</li>
      <li>11</li>
      <li>12</li>
      <li>13</li>
      <li>14</li>
      <li>15</li>
      <li>16</li>
      <li>17</li>
      <li>18</li>
      <li>19</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>1</li>
      <li>2</li>
      <li>3</li>
      <li>4</li>
      <li>5</li>
      <li>6</li>
      <li>7</li>
      <li>8</li>
      <li>9</li>
      <li>10</li>
      <li>11</li>
      <li>12</li>
      <li>13</li>
      <li>14</li>
      <li>15</li>
      <li>16</li>
      <li>17</li>
      <li>18</li>
      <li>19</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>1</li>
      <li>2</li>
      <li>3</li>
      <li>4</li>
      <li>5</li>
      <li>6</li>
      <li>7</li>
      <li>8</li>
      <li>9</li>
      <li>10</li>
      <li>11</li>
      <li>12</li>
      <li>13</li>
      <li>14</li>
      <li>15</li>
      <li>16</li>
      <li>17</li>
      <li>18</li>
      <li>19</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>1</li>
      <li>2</li>
      <li>3</li>
      <li>4</li>
      <li>5</li>
      <li>6</li>
      <li>7</li>
      <li>8</li>
      <li>9</li>
      <li>10</li>
      <li>11</li>
      <li>12</li>
      <li>13</li>
      <li>14</li>
      <li>15</li>
      <li>16</li>
      <li>17</li>
      <li>18</li>
      <li>19</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>1</li>
      <li>2</li>
      <li>3</li>
      <li>4</li>
      <li>5</li>
      <li>6</li>
      <li>7</li>
      <li>8</li>
      <li>9</li>
      <li>10</li>
      <li>11</li>
      <li>12</li>
      <li>13</li>
      <li>14</li>
      <li>15</li>
      <li>16</li>
      <li>17</li>
      <li>18</li>
      <li>19</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>1</li>
      <li>2</li>
      <li>3</li>
      <li>4</li>
      <li>5</li>
      <li>6</li>
      <li>7</li>
      <li>8</li>
      <li>9</li>
      <li>10</li>
      <li>11</li>
      <li>12</li>
      <li>13</li>
      <li>14</li>
      <li>15</li>
      <li>16</li>
      <li>17</li>
      <li>18</li>
      <li>19</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>1</li>
      <li>2</li>
      <li>3</li>
      <li>4</li>
      <li>5</li>
      <li>6</li>
      <li>7</li>
      <li>8</li>
      <li>9</li>
      <li>10</li>
      <li>11</li>
      <li>12</li>
      <li>13</li>
      <li>14</li>
      <li>15</li>
      <li>16</li>
      <li>17</li>
      <li>18</li>
      <li>19</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>1</li>
      <li>2</li>
      <li>3</li>
      <li>4</li>
      <li>5</li>
      <li>6</li>
      <li>7</li>
      <li>8</li>
      <li>9</li>
      <li>10</li>
      <li>11</li>
      <li>12</li>
      <li>13</li>
      <li>14</li>
      <li>15</li>
      <li>16</li>
      <li>17</li>
      <li>18</li>
      <li>19</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>1</li>
      <li>2</li>
      <li>3</li>
      <li>4</li>
      <li>5</li>
      <li>6</li>
      <li>7</li>
      <li>8</li>
      <li>9</li>
      <li>10</li>
      <li>11</li>
      <li>12</li>
      <li>13</li>
      <li>14</li>
      <li>15</li>
      <li>16</li>
      <li>17</li>
      <li>18</li>
      <li>19</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>1</li>
      <li>2</li>
      <li>3</li>
      <li>4</li>
      <li>5</li>
      <li>6</li>
      <li>7</li>
      <li>8</li>
      <li>9</li>
      <li>10</li>
      <li>11</li>
      <li>12</li>
      <li>13</li>
      <li>14</li>
      <li>15</li>
      <li>16</li>
      <li>17</li>
      <li>18</li>
      <li>19</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>1</li>
      <li>2</li>
      <li>3</li>
      <li>4</li>
      <li>5</li>
      <li>6</li>
      <li>7</li>
      <li>8</li>
      <li>9</li>
      <li>10</li>
      <li>11</li>
      <li>12</li>
      <li>13</li>
      <li>14</li>
      <li>15</li>
      <li>16</li>
      <li>17</li>
      <li>18</li>
      <li>19</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>1</li>
      <li>2</li>
      <li>3</li>
      <li>4</li>
      <li>5</li>
      <li>6</li>
      <li>7</li>
      <li>8</li>
      <li>9</li>
      <li>10</li>
      <li>11</li>
      <li>12</li>
      <li>13</li>
      <li>14</li>
      <li>15</li>
      <li>16</li>
      <li>17</li>
      <li>18</li>
      <li>19</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>1</li>
      <li>2</li>
      <li>3</li>
      <li>4</li>
      <li>5</li>
      <li>6</li>
      <li>7</li>
      <li>8</li>
      <li>9</li>
      <li>10</li>
      <li>11</li>
      <li>12</li>
      <li>13</li>
      <li>14</li>
      <li>15</li>
      <li>16</li>
      <li>17</li>
      <li>18</li>
      <li>19</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>1</li>
      <li>2</li>
      <li>3</li>
      <li>4</li>
      <li>5</li>
      <li>6</li>
      <li>7</li>
      <li>8</li>
      <li>9</li>
      <li>10</li>
      <li>11</li>
      <li>12</li>
      <li>13</li>
      <li>14</li>
      <li>15</li>
      <li>16</li>
      <li>17</li>
      <li>18</li>
      <li>19</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>1</li>
      <li>2</li>
      <li>3</li>
      <li>4</li>
      <li>5</li>
      <li>6</li>
      <li>7</li>
      <li>8</li>
      <li>9</li>
      <li>10</li>
      <li>11</li>
      <li>12</li>
      <li>13</li>
      <li>14</li>
      <li>15</li>
      <li>16</li>
      <li>17</li>
      <li>18</li>
      <li>19</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>1</li>
      <li>2</li>
      <li>3</li>
      <li>4</li>
      <li>5</li>
      <li>6</li>
      <li>7</li>
      <li>8</li>
      <li>9</li>
      <li>10</li>
      <li>11</li>
      <li>12</li>
      <li>13</li>
      <li>14</li>
      <li>15</li>
      <li>16</li>
      <li>17</li>
      <li>18</li>
      <li>19</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>1</li>
      <li>2</li>
      <li>3</li>
      <li>4</li>
      <li>5</li>
      <li>6</li>
      <li>7</li>
      <li>8</li>
      <li>9</li>
      <li>10</li>
      <li>11</li>
      <li>12</li>
      <li>13</li>
      <li>14</li>
      <li>15</li>
      <li>16</li>
      <li>17</li>
      <li>18</li>
      <li>19</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>1</li>
      <li>2</li>
      <li>3</li>
      <li>4</li>
      <li>5</li>
      <li>6</li>
      <li>7</li>
      <li>8</li>
      <li>9</li>
      <li>10</li>
      <li>11</li>
      <li>12</li>
      <li>13</li>
      <li>14</li>
      <li>15</li>
      <li>16</li>
      <li>17</li>
      <li>18</li>
      <li>19</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
      <li>20</li>
    </ul>
  </div>
</template>

<script>
import NavBar from "../../components/common/navbar/NavBar";
import BS from 'better-scroll'

export default {
  name: "my",
  components: {
    NavBar
  },
  created(){
    new BS('.content',{
      
    })
  }
};
</script>

<style scope>
.my-nav {
  background-color: var(--color-tint);
  color: white;
}
.content{
  height: 150px;
  background-color: red;
  /* overflow: hidden; */
  /* overflow-y: scroll; */

}
</style>